### ISSUE TITLE
How URL identify the feature is implemented or not

### ISSUE THREAD

**Issue by watilde** [drufball/layered-apis#27]
I'm reading [Supporting algorithm](https://github.com/drufball/layered-apis/blob/master/spec.md#supporting-algorithm) and step five looks like requiring a new extra hook to check if the feature is implemented. My question here is how the paser can get that information? Will URL or somewhere else have something like mapping file for it?

> If the layered API identified by path is implemented by this user agent, return the result of parsing the concatenation of "std:" with identifier.

**Comment by domenic** [comment]
I'm not sure what you mean by extra hook?

The "passer" in this case is the browser. The browser knows what it implements.

This is similar to how you say things like "only expose the navigator.usb property if you implement the Web USB specification".
