### ISSUE TITLE
Load multiple APIs at once

### ISSUE THREAD

**Issue by benjamingr** [drufball/layered-apis#9]
If I want to use let's say... 10 layered APIs I would have to include 10 script tags for all of the dependencies. If I polyfill from different CDNs (or using a browser that isn't 100% optimized for HTTP2 and modules (currently all of them, but not concerned as this is a spec)) the browser opens multiple HTTP connections which slows page load down.

Should there be a specified way to load multiple APIs at once?

**Comment by domenic** [comment]
There already is---using multiple import statements or script tags? That loads them all at once.

**Comment by benjamingr** [comment]
@domenic using multiple imports or script tags can start multiple HTTP connections to the different CDNs

**Comment by domenic** [comment]
Yes, that's true, assuming you are using 10 layered APIs none of which are supported in your browser.

Just like with normal modules, I would not suggest including ten polyfill-of-layered-API modules that are from different CDNs.

**Comment by ojanvafai** [comment]
I wonder if there's something we could do here with web packages. If we have out of band mapping of fallbacks and those fallbacks are then in a web package. Then, in theory, you could construct a system that loads all the fallbacks as a single HTTP request via web packaging.

Lots of "ifs" there. :)

**Comment by domenic** [comment]
@benjamingr ping; still confused what the ask is here.
